export default {
    Errors: '错误',
    Warnings: '警告',
    // bpmn-js-bpmnlint  校验提示
    'Element is missing label/name': '元素缺少标签/名称',
    'Incoming flows do not join': '传入流不连接',
    'Process is missing task node': '流程没有任务节点',
    'Sub process is missing task node': '子流程没有任务节点',
    'Sequence flow is missing condition': '连线缺少条件',
    'Process is missing end event': '流程缺少结束事件',
    'Sub process is missing end event': '子流程缺少结束事件',
    '{errors} Errors, {warnings} Warnings': '{errors} 错误, {warnings} 警告',
    'conditionExpression': '条件表达式',
    'Start event is missing event definition': '启动事件缺少事件定义',
    'eventDefinitions': '事件定义',
    'Flow splits implicitly': '流隐式拆分',
    'Duplicate outgoing sequence flows': '重复的传出序列流',
    'SequenceFlow is a duplicate': 'SequenceFlow是重复的',
    'Process has multiple blank start events':'进程有多个启动事件',
    'Element is not connected':'元素未连接',
    'Toggle linting':'流程校验',
    'Show Simulation Log':'显示流程模拟历史',
    'Play/Pause Simulation':'启动/暂停模拟',
    'Reset Simulation':'重新模拟',
    'Process started':'流程启动',
    'Process finished':'流程完成',
    'The countersign task is missing the countersign type' : '会签节点缺少会签类型',
    'Scale pass system missing scale setting' : '比例通过制缺少比例设置',
    'Countersignature node lacks node staffing' : '会签节点缺少节点人员配置',
    'Auto transfer personnel cannot be empty' : '自动转办人员不能为空',
    'The node rejection strategy is the specified node, and the rejection node cannot be empty' : '节点驳回策略为指定节点，驳回节点不能为空',
    'Expiration processing policy cannot be empty' : '过期处理策略不能为空',
    'Expiration time cannot be empty' : '过期时间不能为空',
}
