export const defaultSettings = {
    processId: `Process_${new Date().getTime()}`,
    processName: '初始化流程',
    processEngine: 'flowable',
    paletteMode: 'enhancement',
    penalMode: 'custom',
    contextPadMode: 'enhancement',
    replaceMenuMode: 'rewrite',
    rendererMode: 'rewrite',
    bg: 'grid-image',
    toolbar: true,
    useMinimap: true,
    useLint: false,
    useMock: true,
    contextmenu: true,
    customContextmenu: true,
    otherModule: true,
    templateChooser: true,
    customTheme: {}
}
